# _config.yml

# Site settings
title: Nagesh Eranki # Replace with your name
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! Here is a list of projects I have worked on in the past
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nagesheranki.github.io/NageshEranki/" # replace with your site's URL
github_username:  NageshEranki

# Theme
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
